dply:
  stage: deploy
  image: python:latest
  script:
    - pip install zensical
    - zensical build --clean 
  pages:
    publish: site
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
